#!/usr/bin/env bash

# --- USAGE
# -- Add your test commands/scripts to prod_test and ci_test under package.json.
# -- When this script runs (any Heroku test environment - i.e. CI)
#    the script will attempt to run production and/or CI tests based on the branch that triggered the CI process.
# -- For example a pull request push would trigger CI tests only
#    but a push to the master branch would trigger production tests as well as CI.

# if we're on the master branch, then run production tests (i.e. codecheck)
const mochapkg = require('./test');
mochapkg.run();
